### ISSUE TITLE
No active development?

### ISSUE THREAD

**Issue by MickL** [jeetiss/image-fns#11]
Hey,
if you don't activly develop this, could you please free the npm namespace `image-fns`? I did work on a image library and would love to use that namespace according to `date-fns` which is also a TypeScript library but for dates.

My npm name is `mickl`

**Comment by Zmoki** [comment]
Hi @MickL 

We working on `image-fns`. It's not dead. It's just starting to live. This lib provides some functions to work with images in a browser. Like, shrink or check transparency.

Feel free to contribute. But, we can‘t free name for you.

**Comment by MickL** [comment]
Maybe checkout my project if thats sonething to collaborate? Currently it is calldd MickL/ts-image-processor
